version: "3"
services: 
  oci:
    image: yin26287903/java_oci_manage_docker
    container_name: java_oci_manage_docker
    tty: true
    ports:
      - 9527:9527
    volumes:
      - ./config/client_config:/app/client_config
      - ./config/key.pem:/app/key.pem
    restart: always