name: BuildDockerfileImage

on:
  workflow_dispatch:
  schedule:
  repository_dispatch:
    types: build_docker_image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Dockerfile VERSION
        run: |
          VERSION=$(curl -s https://api.github.com/repos/semicons/java_oci_manage/releases/latest | jq -r .tag_name | sed 's/v//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
        id: get_version

      - name: Check if Docker image exists
        id: check_image_exists
        run: |
          IMAGE_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" https://hub.docker.com/v2/repositories/yin26287903/java_oci_manage_docker/tags/${{ env.VERSION }})
          if [ "$IMAGE_EXISTS" -eq "200" ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        if: env.exists == 'false'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            yin26287903/java_oci_manage_docker:${{ env.VERSION }}
            yin26287903/java_oci_manage_docker:latest
