name: 构建Docker镜像

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: build_docker_image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆 仓库
        uses: actions/checkout@v3

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录 DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 获取 最新版本号
        run: |
          VERSION=$(curl -s https://api.github.com/repos/semicons/java_oci_manage/releases/latest | jq -r .tag_name | sed 's/v//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo -e "\033[0;32m当前版本: $VERSION\033[0m"
        id: get_version

      - name: 检查 Docker 镜像是否存在
        id: check_image_exists
        run: |
          IMAGE_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" https://hub.docker.com/v2/repositories/yin26287903/java_oci_manage_docker/tags/${{ env.VERSION }})
          if [ "$IMAGE_EXISTS" -eq "200" ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: 构建并推送 Docker 镜像
        if: env.exists == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            yin26287903/java_oci_manage_docker:${{ env.VERSION }}
            yin26287903/java_oci_manage_docker:latest
